### ISSUE TITLE
Links in forum don't work 

### ISSUE THREAD

**Issue by lck-git** [cmb69/forum_xh#40]
See [CMSimple_XH Forum](https://cmsimpleforum.com/viewtopic.php?f=16&t=17612)

Solution:
Change
https://github.com/cmb69/forum_xh/blob/78e30c7fb83859db93e213eac9ab2439b75323da/forum.min.js#L59

to

`each.call(document.querySelector(".forum_container:not(.forum_comment)"),function(container){`

**Comment by cmb69** [comment]
Thank you very much!

**Comment by cmb69** [comment]
Nah, that doesn't have the desired result. We need to select all `a`s in `.forum_container`, which are not descendents of `.forum_comment`.
