### ISSUE TITLE
System Check shows confusing path

### ISSUE THREAD

**Issue by lck-git** [cmb69/forum_xh#45]
https://github.com/cmb69/forum_xh/blob/4403be886e83e585ede5e16a7ff4e091c130b7a3/classes/SystemCheckService.php#L75

Warum ergibt das in der Systemprüfung
`Prüfe, dass './content/./forum/' schreibbar ist … OK`

sollte doch eigentlich sein
`Prüfe, dass './content/forum/' schreibbar ist … OK`

**Comment by cmb69** [comment]
Wegen
https://github.com/cmb69/forum_xh/blob/4403be886e83e585ede5e16a7ff4e091c130b7a3/classes/Plugin.php#L65

Das sollte besser normalisiert werden. Bei Zweitsprachen wird es nämlich wirklich garstig: './content/de/../forum' (statt './content/forum').
